# Simple workflow for deploying static content to GitHub Pages
name: Github Pages Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  deploy:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Install and build
          run: npm install && npm run build

        - name: Deploy
          uses: RongxiM/github-pages-deploy-action@4.4.0
          with:
            branch: gh-pages # The branch the action should deploy to
            folder: build # The folder the aciton should deploy
